name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run clone and restart discord bot on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e
            cd ~/chwopcha
            echo '------------------------Copy repo------------------------'
            git pull origin main || { echo "Git pull failed"; exit 1; }
            echo '------------------------Switch to Node.js 20------------------------'
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            nvm use 20
            echo '------------------------Npm install------------------------'
            npm cache clean --force
            npm install
            echo '------------------------Restart discord bot------------------------'
            pm2 reload chwopcha
            echo '------------------------Check logs------------------------'
            pm2 logs chwopcha --lines 10
